webapplication/urls.py
from django.contrib import admin
from django.urls import path
from crudapplication import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('emp/', views.emp),
    path('show/', views.show),
    path('edit/<int:id>', views.edit),
    path('update/<int:id>', views.update),
    path('delete/<int:id>', views.delete),
]

crudapplication/models.py
from django.db import models

# Create your models here.
class Employee(models.Model):
    eid =models.CharField(max_length=50)
    ename =models.CharField(max_length=100)
    eemail =models.EmailField()
    econtact =models.CharField(max_length=15)
    class Meta:
        db_table = "employee"

crudapplication/forms.py
from django import forms
from crudapplication.models import Employee
class EmployeeForm(forms.ModelForm):
    class Meta:
        model = Employee
        fields = "__all__"

crudapplication/views.py
from django.shortcuts import render,redirect
from crudapplication.forms import EmployeeForm
from crudapplication.models import Employee
def emp(request):
    if request.method=="POST":
        form = EmployeeForm(request.POST)
        if form.is_valid():
            try:
                form.save()
                return redirect('/show/')
            except:
                pass
    else:
        form = EmployeeForm()
    return render(request, "index.html", {'form' : form})
def show(request):
    employees = Employee.objects.all()
    return render(request,"show.html",{'employees':employees})
def edit(request,id):
    employee = Employee.objects.get(id=id)
    return render(request, "edit.html", {'employee':employee})
def update(request,id):
    employee = Employee.objects.get(id=id)
    form = EmployeeForm(request.POST, instance=employee)
    if form.is_valid():
        form.save()
        return(redirect('/show/'))
    return(render(request,'edit.html',{'employee':employee}))
def delete(request,id):
    employee = Employee.objects.get(id=id)
    employee.delete()
    return(redirect('/show/'))

crudapplication/templates/edit.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <title>Employee Records</title>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    {% load static %}
    <link
      rel="stylesheet"
      type="text/css"
      media="screen"
      href="{% static '/style.css' %}"
    />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
      integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
      crossorigin="anonymous"
    />
  </head>
  <body>
    <form method="POST" class="post-form" action="/update/{{employee.id}}">
      {% csrf_token %}
      <div class="container">
        <br />

        <div class="form-group row">
          <label class="col-sm-l col-form-label"></label>
          <div class="col-sm-4">
            <h3>Update Details</h3>
          </div>
        </div>

        <div class="form-group">
          <div class="row">
            <div class="col-sm-2">Employee ID:</div>
            <div class="col-sm-2">
              <input
                type="text"
                name="eid"
                id="id_eid"
                required
                maxlength="50"
                value="{{employee.eid}}"
              />
            </div>
          </div>
        </div>

        <div class="form-group">
          <div class="row">
            <div class="col-sm-2">Employee Name:</div>
            <div class="col-sm-2">
              <input
                type="text"
                name="ename"
                id="id_ename"
                required
                maxlength="100"
                value="{{employee.ename}}"
              />
            </div>
          </div>
        </div>
        <div class="form-group">
          <div class="row">
            <div class="col-sm-2">Employee Email:</div>
            <div class="col-sm-2">
              <input
                type="email"
                name="eemail"
                id="id_eemail"
                required
                maxlength="100"
                value="{{employee.eemail}}"
              />
            </div>
          </div>
        </div>
        <div class="form-group">
          <div class="row">
            <div class="col-sm-2">Employee Contact:</div>
            <div class="col-sm-2">
              <input
                type="text"
                name="econtact"
                id="id_econtact"
                required
                maxlength="100"
                value="{{employee.econtact}}"
              />
            </div>
          </div>
        </div>
        <div class="form-group row">
          <label class="col-sm-l col-form-label"></label>
          <div class="col-sm-4">
            <button type="submit" class="btn btn-success">Update</button>
          </div>
        </div>
      </div>
    </form>
  </body>
</html>

crudapplication/templates/index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <title>Index</title>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    {% load static %}
    <link
      rel="stylesheet"
      type="text/css"
      media="screen"
      href="{% static '/style.css' %}"
    />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
      integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
      crossorigin="anonymous"
    />
  </head>
  <body>
    <form method="POST" class="post-form" action="/emp/">
      {% csrf_token %}
      <div class="container">
        <div class="form-group row">
          <label class="col-sm-l col-form-label"></label>
          <div class="col-sm-4"><h3>Enter Details</h3></div>
        </div>

        <div class="form-group">
          <div class="row">
            <div class="col-sm-2">Employee ID:</div>
            <div class="col-sm-2">{{form.eid}}</div>
          </div>
        </div>
        
        <div class="form-group">
          <div class="row">
            <div class="col-sm-2">Employee Name:</div>
            <div class="col-sm-2">{{form.ename}}</div>
          </div>
        </div>
        <div class="form-group">
          <div class="row">
            <div class="col-sm-2">Employee Email:</div>
            <div class="col-sm-2">{{form.eemail}}</div>
          </div>
        </div>
          <div class="form-group">
            <div class="row">
              <div class="col-sm-2">Employee Contact:</div>
              <div class="col-sm-2">{{form.econtact}}</div>
            </div>
          </div>
          <div class="form-group">
            <div class="row">
              <div class="col-sm-6">
                <button type="submit" class="btn btn-primary">Submit</button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </form>
  </body>
</html>

crudapplication/templates/show.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <title>Employee Records</title>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link
      rel="stylesheet"
      type="text/css"
      media="screen"
      href="{% static '/style.css' %}"
    />
    <script
      src="https://code.jquery.com/jquery-3.5.1.min.js"
      integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0="
      crossorigin="anonymous"
    ></script>
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
      integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      type="text/css"
      href="https://cdn.datatables.net/1.10.21/css/jquery.dataTables.css"
    />

    <script
      type="text/javascript"
      charset="utf8"
      src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.js"
    ></script>
  </head>
  <body>
    <br />
    <br />
    <center><a href="/emp" class="btn btn-primary">Add New Record</a></center>
    <br />
    <br />
    <table class="table table-striped table-borderd table-sm">
      <thead class="thead-dark">
        <tr>
          <th>Employee ID</th>
          <th>Employee Name</th>
          <th>Employee Email</th>
          <th>Employee Contact</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        {% for employee in employees %}
        <tr>
          <td>{{ employee.eid }}</td>
          <td>{{ employee.ename }}</td>
          <td>{{ employee.eemail }}</td>
          <td>{{ employee.econtact }}</td>
          <td>
            <a href="/edit/{{employee.id}}"
              ><span class="glyphicon glyphicon-pencil">Edit</span></a
            >
            <a href="/delete/{{employee.id}}">Delete</a>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    <script>
      $(document).ready(function () {
        $(".table").DataTable();
      });
    </script>
  </body>
</html>